travis:
  secure:
    BINSTAR_TOKEN: mOHt0/o+4O2Zv67M/TLs5V1awdsfDRlk3yrmBzWy82itIuTMpwSBDJ/Ya88oEnq96Xi6Fl4VCtSUDD9F6C8zCHrPxxGP9cqlU9HBPWXKvh56Fe0i9A/L/vyqan6Vfn8BXJ6F8y/LUyGJJuMDnrhfKQ9fTgsU8igYcxKtabQyuSiRCX9fiRJQevgZ/D2EwobZhVyt4k6eMFr+DtTnI8UbOS1NVyv68MCAlROiF7OeqKD8BeZncLX5GmG5K5jlGQGcQGTWmUfmc3a+PPmD84elFDzZw3FgEER6kkkVHT2hcplptmMx5ADTiypC1kGDNDMlnVR+PbnbGCBjV10+4APhQEJ52PL2EXVFgVGEfML0nRumBAYRwmuyQ2hzZYWJz9AyY8vQ78rO09Mv27TDHPwUgeYOXf8kyoSfcsykETMlH1ODULGS4HxJDIVorPxBOjHjZzsVmG5sLSkeOzG6nW/YNLpqTt1a3PHXWPoDcKq3Pw28DwfbB5v+GfBEqD9BleBTnWbXMtF17m0YwijW56OhbEpveQPdHgGF79bYVnIk1Nu15tq9Z+fIbTF+15rd4jWAS6stOkn6CYx63xH0ui4yrKWcprKUHisyvaQJa73jcMKPbVHA8FEktTr+kyYZ+rnI/t4iLVNrRcp4AO87Cyve1rI0qUdQTmaifLX0ErTZrso=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
